[CessChain]
# CESS chain address
ChainAddr = "ws://106.15.44.155:9949/"

[MinerData]
# Total space used to store files, the unit is GB
StorageSpace   = 1024
# Path to the mounted disk where the data is saved
MountedPath    = "/"
# The IP address of the machine's public network used by the mining program
ServiceAddr    = "127.0.0.1"
# Port number monitored by the mining program
ServicePort    = 15001
# Public key of revenue account
RevenuePuK     = ""
# Phrase words or seeds for transaction account
TransactionPrK = ""
