# The rpc address of the chain node
RpcAddr      = ""

# Path to the mounted disk where the data is saved
MountedPath  = ""

# Total space used to store files, the unit is GB
StorageSpace = 1000

# The IP address of the machine's public network used by the mining program
ServiceAddr  = ""
# Port number monitored by the mining program
ServicePort  = 15001
# The address of income account
IncomeAcc    = ""
# phrase or seed of the signature account
SignaturePrk = ""
