[cessChain]
# CESS chain address
rpcAddr = "ws://106.15.44.155:9949/"

[minerData]
# Total space used to store files, the unit is GB.
storageSpace           = 1024
# Path to the mounted disk where the data is saved
mountedPath            = "/"
# The IP address of the machine's public network used by the mining program.
serviceIpAddr          = "127.0.0.1"
# Port number monitored by the mining program.
servicePort           = 15001
# Public key of income account.
incomeAccountPubkey    = ""
# Phrase words or seeds for identity accounts.
idAccountPhraseOrSeed  = ""
