[CessChain]
# CESS chain address
ChainAddr = ""

[MinerData]
# Total space used to store files, the unit is GB
StorageSpace   = 0
# Path to the mounted disk where the data is saved
MountedPath    = ""
# The IP address of the machine's public network used by the mining program
ServiceAddr    = ""
# Port number monitored by the mining program
ServicePort    = 15001
# Public key of revenue account
RevenuePuK     = ""
# Phrase words or seeds for transaction account
TransactionPrK = ""
